Controllers/NoticiaController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieAppV2.Data;
using MovieAppV2.Models;

namespace MovieAppV2.Controllers
{
    public class NoticiaController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly MovieContext _context;

        public NoticiaController(ILogger<HomeController> logger,
            MovieContext context)
        {
                _logger = logger;
                _context = context;
        }

        public IActionResult AgregarNoticia(){
                return View();
        }

        [HttpPost]
        public IActionResult AgregarNoticia (Noticia objNoticia)
        {
            objNoticia.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
            if(ModelState.IsValid){
                _context.Add(objNoticia);
                _context.SaveChanges();
                return RedirectToAction("verNoticia");
            }
            
            return View();
            

            
        }

         public IActionResult EditarNoticia(int? id)
        {
            if(id == null){
                return NotFound();
            }
            var noticia = _context.Noticias.Find(id);
            if(noticia == null){
                return NotFound();
            }
            return View(noticia);
        }

        [HttpPost]
        public IActionResult EditarNoticia(int id, Noticia objNoticia)
        {
            if (ModelState.IsValid)
            {
                objNoticia.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
                _context.Update(objNoticia);
                _context.SaveChanges();
                return RedirectToAction("VerNoticia");
            }
            return View();
        }

        public IActionResult BorrarNoticia(int? id)
        {
            var noticia = _context.Noticias.Find(id);
            _context.Noticias.Remove(noticia);
            _context.SaveChanges();
            return RedirectToAction(nameof(VerNoticia));
        }

        public IActionResult VerNoticia(){
            var listNoticia=_context.Noticias.OrderBy(s=>s.ID) .ToList();
            return View(listNoticia);
        }

        

       



       
        public IActionResult VerNoticia2(){
                return View();
        }
        public IActionResult VerNoticia3(){
                return View();
        }
      
    }
}

Controllers/Quiz2Controller.cs
using Microsoft.AspNetCore.Mvc;
 
namespace MovieAppV2.Controllers
{
    public class Quiz2Controller : Controller
    {
        public IActionResult Preguntas(){
            return View();
        }
    }
}

Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using MovieAppV2.Models;

namespace MovieAppV2.Controllers
{
    public class QuizController : Controller
    {
      public IActionResult Trivia()
      {
        return View();
      }

      public IActionResult ResultadoCreate(Quiz objquiz)
      {
        objquiz.ResulFinal = objquiz.RPg1 + objquiz.RPg2 + objquiz.RPg3;
        
        if(objquiz.ResulFinal>2)
        {
        objquiz.Mensaje = "Tus Aciertos son: " + objquiz.ResulFinal + " Felicidades Acertastes todas";
        }
        else
        {
        objquiz.Mensaje = "Tus Aciertos son: " + objquiz.ResulFinal;
        }

        return View("Trivia",objquiz);
      }   
    }
}

Controllers/UsuarioController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieAppV2.Data;
using MovieAppV2.Models;

namespace MovieAppV2.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly MovieContext _context;
        private UserManager<IdentityUser> _um;
        private SignInManager<IdentityUser> _sim;
        public UsuarioController(MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim)
        {
            _context = context;
            _um = um;
            _sim = sim;
        }
        public IActionResult Index()
        {
            var listPelicula=_context.Peliculas.OrderBy(s=>s.ID) .ToList();
            return View(listPelicula);
        }

        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registro(string username, string pwd, Usuario infouser)
        {
            infouser.Username = username;
            infouser.Pwd = pwd;
            if(ModelState.IsValid){
                var IdentityUser = new IdentityUser(username);
                var result =_um.CreateAsync(IdentityUser,pwd).Result;
                if(result.Succeeded)
                {
                    _context.Add(infouser);
                    _context.SaveChanges();
                    return RedirectToAction("login");
                }else{
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("usuario", error.Description);
                    }
                    var result2 =_um.DeleteAsync(IdentityUser).Result;
                    return View();
                }
            }
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username, string pwd)
        {
            var result = _sim.PasswordSignInAsync(username,pwd,false,false).Result;
            if(result.Succeeded)
            {
                return RedirectToAction("index","home");
            }
            ModelState.AddModelError("usuario","Datos incorrectos");
            return View();
        }
        public async Task<IActionResult> logout()
        {
            await _sim.SignOutAsync();
            return RedirectToAction("index","home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieAppV2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/axcel.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="icon" href="/movie.ico" sizes="16x16">
    <script src="https://use.fontawesome.com/ebea311352.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar navbar-dark bg-dark border-bottom border-dark box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="/movie.ico" class="d-inline-block align-top" width="30px" height="30px"> MovieAppV2</a>
                <button class="switch p-t-1" id="switch">
                    <span>☺</span>
                    <span>☻</span>
                </button>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item active">-->
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Quiz2" asp-action="Preguntas">Quiz2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Privacy">Quienes Somos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Quiz" asp-action="Trivia">Quiz</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" data-toggle="dropdown" role="button" >Películas</a>
                                <div class="dropdown-menu bg-dark">
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Pelicula" asp-action="AgregarPelicula">Agregar nueva película</a>
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Pelicula" asp-action="Catalogo">Catálogo</a>
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Pelicula" asp-action="MisPeliculas">Mis peliculas</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" data-toggle="dropdown" role="button" >Noticia</a>
                                <div class="dropdown-menu bg-dark">
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Noticia" asp-action="AgregarNoticia">Agregar Noticia</a>
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Noticia" asp-action="VerNoticia">Noticias del Canal</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link active bg-dark text-light" asp-controller="usuario" asp-action="logout">Cerrar Sesion (@User.Identity.Name)</a>
                            </li>
                        }else
                        {
                            <li class="nav-item">
                                    <a class="nav-link active bg-dark text-light" asp-controller="Pelicula" asp-action="Catalogo">Catálogo</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link active bg-dark text-light" asp-controller="Noticia" asp-action="VerNoticia">Noticias del Canal</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" data-toggle="dropdown" role="button" >Usuarios</a>
                                <div class="dropdown-menu bg-dark">
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Usuario" asp-action="Login">Login</a>
                                    <a class="dropdown-item bg-dark text-light" asp-controller="Usuario" asp-action="Registro">Registro</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="fondo">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top p-2 text-muted fondofot" style="width: 100%;">
        <div class="container">
            &copy; 2020 - MovieAppV2 - <a asp-area="s" asp-controller="Home" asp-action="Privacy">Quienes Somos</a>
        </div>
    </footer>
    <script src="https://use.fontawesome.com/ebea311352.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>