Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieAppV2.Models
{
    public class Pelicula
    {
        public int ID { get; set; }

        [Required(ErrorMessage="Debe ingresar un Titulo")]
        public string Titulo { get; set; }

        [Required(ErrorMessage="Debe ingresar un director")]
        public string Director { get; set; }

        [Required(ErrorMessage="Debe ingresar un pais")]
        public string Pais { get; set; }

        [Required(ErrorMessage="Ingrese un año")]
        public int? Año { get; set; }

        [Required(ErrorMessage="Especifique el genero")]
        public string Genero { get; set; }

        [Required(ErrorMessage="Ingrese la duracion")]
        public int? Duracion { get; set; }

        [Required(ErrorMessage="Debe ingresar una clasificacion")]
        public string Clasificacion { get; set; }

        [Required(ErrorMessage="Debe ingresar un idioma")]
        public string Idioma { get; set; }

        [Required(ErrorMessage="Debe ingresar una sinopsis")]
        public string Sinopsis { get; set; }
        public string Imagen { get; set; }
        public string Trailer { get; set; }
        public Usuario Usuario { get; set; }
        public int UsuarioId { get; set; }
        public List<Reseña> Reseñas { get; set; }
    }
}

Controllers/PeliculaController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.Extensions.Logging;
using MovieAppV2.Models;
using System.Collections.Generic;
using MovieAppV2.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace MovieAppV2.Controllers
{
    public class PeliculaController : Controller
    {
        
        private readonly ILogger<HomeController> _logger;
        private readonly MovieContext _context;
        private UserManager<IdentityUser> _um;
        private SignInManager<IdentityUser> _sim;
        public PeliculaController(ILogger<HomeController> logger,
            MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim)
        {
            _logger = logger;
            _context = context;
            _um = um;
            _sim = sim;
        }
        public IActionResult AgregarPelicula()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AgregarPelicula(Pelicula objPelicula)
        {
            objPelicula.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
            if(ModelState.IsValid)
            {
                if(objPelicula.Trailer.Length>42){
                objPelicula.Trailer=ConvertirPelicula(objPelicula.Trailer);
                }
                _context.Add(objPelicula);
                _context.SaveChanges();
                return RedirectToAction("Catalogo");
            }else
            return View(objPelicula);
                
            
            /*
            TempData["Nombre de pelicula"]=objPelicula.Titulo;  
            TempData["Nombre del Director"]=objPelicula.Director;
            TempData["Año"]=objPelicula.Año;
            */
        }
        public string ConvertirPelicula(string urlpelicula){
            urlpelicula=urlpelicula.Substring(32,11);
            var peliculaurl="https://www.youtube.com/embed/" + urlpelicula;
            return peliculaurl;
        }

        public IActionResult EditarPelicula(int? id)
        {
            if(id == null){
                return NotFound();
            }
            var pelicula = _context.Peliculas.Find(id);
            if(pelicula == null){
                return NotFound();
            }
            return View(pelicula);
        }

        [HttpPost]
        public IActionResult EditarPelicula(int id, Pelicula objPelicula)
        {
            objPelicula.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
            if (ModelState.IsValid)
            {
                if(objPelicula.Trailer.Length>42){
                    objPelicula.Trailer=ConvertirPelicula(objPelicula.Trailer);
                }
                _context.Update(objPelicula);
                _context.SaveChanges();
                return RedirectToAction("Catalogo");
            }
            return View();
        }
        
        public IActionResult BorrarPelicula(int? id)
        {
            var pelicula = _context.Peliculas.Find(id);
            _context.Peliculas.Remove(pelicula);
            _context.SaveChanges();
            return RedirectToAction(nameof(Catalogo));
        }
        public IActionResult Catalogo(){
            var listPelicula=_context.Peliculas.OrderBy(s=>s.ID) .ToList();
            return View(listPelicula);
        }
        public IActionResult VistaPelicula(int? id)
        {
            var pelicula = _context.Peliculas.Find(id);
            ViewBag.resenas = false;
            if (_context.Reseñas.Where(x => x.PeliculaId.Equals(id)).Count() > 0)
            {
                ViewBag.resenas = true;
                Random rnd = new Random();
                int nrouser = rnd.Next(_context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).OrderBy(x=>x.Id).ToList().First().Id,_context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).OrderBy(x => x.Id).ToList().Last().Id);
                ViewBag.fecha = _context.Reseñas.Find(nrouser).Fecha.ToString();
                ViewBag.estrellitas = _context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).FirstOrDefault(x=>x.Id.Equals(nrouser)).Estrellas;
                ViewBag.nombreusuario = _context.Usuarios.Where(x => x.Id.Equals(_context.Reseñas.Find(nrouser).UsuarioId)).First().Username;
                ViewBag.resenausuario = _context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).FirstOrDefault(x=>x.Id.Equals(nrouser)).Comentario;
                ViewBag.fecha = _context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).FirstOrDefault(x=>x.Id.Equals(nrouser)).Fecha;
            }
            if(pelicula == null){
                return NotFound();
            }
            return View(pelicula);
        }
        [HttpPost]
        public IActionResult Catalogo(string idfiltro, string filtro)
        {
            var listClientes = _context.Peliculas.OrderBy(s => s.ID).ToList();
            if(idfiltro == "titulo"){
                listClientes=_context.Peliculas.Where(c => c.Titulo.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.ID) .ToList();
            }else if(idfiltro == "director"){
                listClientes=_context.Peliculas.Where(c => c.Director.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.ID) .ToList();
            }else{
                listClientes=_context.Peliculas.Where(c => c.Genero.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.ID) .ToList();
            }
            // var listClientes=_context.Clientes.Where(c => c.Nombre.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.Id) .ToList();
            return View(listClientes);
        }
        public IActionResult MisPeliculas()
        {
            var listapeliculas = _context.Peliculas.OrderBy(x => x.ID).Where(p => p.Usuario.Username.Equals(User.Identity.Name)).ToList();
            return View(listapeliculas);
        }
        [HttpPost]
        public IActionResult MisPeliculas(string idfiltro, string filtro)
        {
            var listapeliculas = _context.Peliculas.OrderBy(x => x.ID).Where(p => p.Usuario.Username.Equals(User.Identity.Name)).ToList();
            if(idfiltro == "titulo"){
                listapeliculas=_context.Peliculas.Where(c => c.Titulo.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.ID) .ToList();
            }else if(idfiltro == "director"){
                listapeliculas=_context.Peliculas.Where(c => c.Director.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.ID) .ToList();
            }else{
                listapeliculas=_context.Peliculas.Where(c => c.Genero.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.ID) .ToList();
            }
            return View(listapeliculas);
        }

        
    }
}
    /*
        public IActionResult Catalogo()
        {

            
            ViewData["Nombre de pelicula"]=TempData["Nombre de pelicula"];
            ViewData["Nombre del Director"]=TempData["Nombre del Director"];
            ViewData["Año"]=TempData["Año"];
            return View();
            
        }
*/


        /*
        public IActionResult GetPelicula()
        {
            var listCatalogo = new List<Pelicula>();
            listCatalogo.Add(
                new Pelicula(){ Titulo="Virus",Director="Aashiq Abu", Pais="Corea del Sur", Año=2013, Genero="Suspenso",Duracion=121, Clasificacion="R", Idioma="Coreano", Sinopsis="El distrito surcoreano de Bundang-gu debe enfrentar una repentina proliferación del virus H5N1, enfermedad que mata a sus víctimas tras 36 horas de alojarse en el organismo. El virus, transmitido por vía respiratoria, llega al distrito luego de que un grupo de inmigrantes ilegales llevarán la enfermedad hasta allí al ser transportados en un contenedor. Kang Ji-goo conocerá en medio del caos a la hermosa Kim In-hae, con la que deberá enfrentar esta terrible y mortal amenaza." });
            listCatalogo.Add(
                new Pelicula(){ Titulo="It Capítulo Dos",Director="	Andrés Muschietti", Pais="	Estados Unidos", Año=2019, Genero="Terror",Duracion=169, Clasificacion="+14", Idioma="Ingles", Sinopsis="En el misterioso pueblo de Derry, un malvado payaso llamado Pennywise vuelve 27 años después para atormentar a los ya adultos miembros del Club de los Perdedores, que ahora están más alejados unos de otros." });
            listCatalogo.Add(
                new Pelicula(){ Titulo="Train to Busan",Director="Yeon Sang-ho", Pais="Corea del Sur", Año=2016, Genero="Drama",Duracion=118, Clasificacion="R", Idioma="Coreano", Sinopsis="Un brote viral misterioso pone a Corea en estado de emergencia. Sok-woo y su hija Soo-ahn suben al KTX, un tren rápido que une los 442 km que separan Seúl de Busan, una ciudad que se defiende con éxito de la epidemia. Sin embargo, justo en el momento de su partida, la estación es invadida por zombis que matan al conductor del tren y a otros pasajeros." });
            return View("Catalogo",listCatalogo);
        }
        */

Controllers/ReseñaController.cs
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieAppV2.Data;
using MovieAppV2.Models;

namespace MovieAppV2.Controllers
{
    public class ReseñaController : Controller
    {
        private readonly MovieContext _context;
        private UserManager<IdentityUser> _um;
        private SignInManager<IdentityUser> _sim;
        public ReseñaController(MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim)
        {
            _context = context;
            _um = um;
            _sim = sim;
        }
        public IActionResult Resena(int? peli)
        {
            if(peli == null)
            {
                return NotFound();
            }
            var resena = _context.Peliculas.Find(peli);
            var infopeli = _context.Reseñas.Find(peli);
            // var infopeli2 = _context.Reseñas.Include(x=> x.Pelicula).Include(y=> y.Usuario).SingleOrDefault(z=> z.Pelicula.ID == peli);
            ViewBag.imgpeli = resena.Imagen;
            ViewBag.titulopeli = resena.Titulo;
            return View();
        }
        [HttpPost]
        public IActionResult resena(int peli, Reseña objResena)
        {
            var resena = _context.Peliculas.Find(peli);
            ViewBag.imgpeli = resena.Imagen;
            ViewBag.titulopeli = resena.Titulo;
            
            if(ModelState.IsValid)
            {
                objResena.Fecha = System.DateTime.Now;
                objResena.PeliculaId = peli;
                objResena.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
                // return BadRequest(objResena);
                _context.Add(objResena);
                _context.SaveChanges();
                return RedirectToAction("Catalogo","Pelicula");
            }
            return View();
        }
        public IActionResult VerResenas(int peli)
        {
            var listaResenas = _context.Reseñas.Include(q=>q.Pelicula).Include(w=>w.Usuario).Where(p=>p.PeliculaId.Equals(peli)).OrderBy(x=>x.Id).ToList();
            var pelicula = _context.Peliculas.Find(peli);
            ViewBag.peli = pelicula.Titulo;
            return View(listaResenas);
        }
    }
}

Controllers/UsuarioController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieAppV2.Data;
using MovieAppV2.Models;

namespace MovieAppV2.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly MovieContext _context;
        private UserManager<IdentityUser> _um;
        private SignInManager<IdentityUser> _sim;
        public UsuarioController(MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim)
        {
            _context = context;
            _um = um;
            _sim = sim;
        }
        public IActionResult Index()
        {
            var listPelicula=_context.Peliculas.OrderBy(s=>s.ID) .ToList();
            return View(listPelicula);
        }

        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registro(string username, string pwd, Usuario infouser)
        {
            infouser.Username = username;
            infouser.Pwd = pwd;
            if(ModelState.IsValid){
                var IdentityUser = new IdentityUser(username);
                var result =_um.CreateAsync(IdentityUser,pwd).Result;
                if(result.Succeeded)
                {
                    _context.Add(infouser);
                    _context.SaveChanges();
                    return RedirectToAction("login");
                }else{
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("usuario", error.Description);
                    }
                    var result2 =_um.DeleteAsync(IdentityUser).Result;
                    return View();
                }
            }
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username, string pwd)
        {
            var result = _sim.PasswordSignInAsync(username,pwd,false,false).Result;
            if(result.Succeeded)
            {
                return RedirectToAction("index","home");
            }
            ModelState.AddModelError("usuario","Datos incorrectos");
            return View();
        }
        public async Task<IActionResult> logout()
        {
            await _sim.SignOutAsync();
            return RedirectToAction("index","home");
        }
    }
}

Views/Pelicula/AgregarPelicula.cshtml
@* <link rel="stylesheet" href="~/css/agregarpeli.css" /> *@
@model MovieAppV2.Models.Pelicula;
@{
    ViewData["Title"] = "Agregar película";
}
<h1>@ViewData["Title"]</h1>

<div class="container">
    <form method="post">
        <div asp-validation-summary="All"></div>
        <div class="form-group">
            <label asp-for="Titulo">Título</label>
            <input asp-for="Titulo" class="form-control" placeholder="Título">
        </div>

        <div class="form-group">
            <label asp-for="Director">Director</label>
            <input asp-for="Director" class="form-control" placeholder="Director(es)">
        </div>

        <div class="form-group">
            <label asp-for="Pais">País</label>
            <input asp-for="Pais" class="form-control" placeholder="País">
        </div>

        <div class="form-group">
            <label asp-for="Año">Año</label>
            <input asp-for="Año" class="form-control" placeholder="Año de estreno">
        </div>

        <div class="form-group">
            <label asp-for="Genero">Seleccione Género</label>
            <select asp-for="Genero" class="form-control">
                <option>Acción</option>
                <option>Comedia</option>
                <option>Drama</option>
                <option>Romance</option>
                <option>Ciencia y ficción</option>
                <option>Terror</option>
                <option>Suspenso</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Duracion">Duración</label>
            <input asp-for="Duracion" class="form-control" placeholder="En Minutos">
        </div>

        <div class="form-group">
            <label asp-for="Clasificacion">Clasificación</label>
            <input asp-for="Clasificacion" class="form-control">
        </div>



        <div class="form-group">
            <label asp-for="Idioma">Idioma</label>
            <select asp-for="Idioma" class="form-control">
                <option>Inglés</option>
                <option>Español</option>
                <option>Español latino</option>
                <option>Chino</option>
                <option>Coreano</option>
            </select>
        </div>
    
        <div class="form-group">
            <label asp-for="Sinopsis">Sinopsis</label>
            <textarea asp-for="Sinopsis" placeholder="Sinopsis de la pelicula" class="form-control"cols="30" rows="10"></textarea>        
        </div>

        <div class="form-group">
            <label asp-for="Imagen">Url de la imagen</label>
            <input asp-for="Imagen" class="form-control">
        </div>


        <div class="form-group">
            <label asp-for="Trailer">Url del trailer</label>
            <input  asp-for="Trailer" class="form-control" required>
        </div>
        

        <div class="text-center">
            
            <input type="submit" class="btn btn-primary" value="Agregar película" >
    </form>
            <input type="submit" class="btn btn-danger" value="Volver" onclick="location.href='@Url.Action("Index","Home")'">
        </div>
</div>

Views/Pelicula/Catalogo.cshtml
@* <link rel="stylesheet" href="~/css/EstilosCatalogo.css"> *@

@model List<Pelicula>

<h2 class="text-center">Lista de Películas</h2>


<style>
    a {
    color: #ffffff;
    text-decoration: none;
}
    a:hover 
{
     color:#ffffff; 
     text-decoration:none; 
     cursor:pointer;  
}


@* img:hover{
    width: 220px;
    height: 290px;
} *@

img{
    box-shadow: 5px 5px 10px
    rgba(0, 0, 0, 0.40);
}


</style>


<form method="POST">
    <label >Filtrar por :</label>
    <select name="idfiltro">
        <option value="titulo">Título</option>
        <option value="director">director</option>
        <option value="genero">Género</option>``
    </select>
    <input type="text" name="filtro" required>
    <button class="btn btn-info">Filtrar</button>
</form>

<div class="table-responsive">
    <table class="table">
        @for(var i=0;i<(Model.Count); i+=2)
        {
            <tr>
                @for(var j=0; j<2; j++){
                    @if(i+j<Model.Count){
                        <td scope="col">
                            <div class="portafolio-container"> 
                                <a asp-action="VistaPelicula" asp-route-id="@Model[i+j].ID">     
                                    <img class="portafolio-img" width="180px" height="250px" src="@Html.DisplayFor(modelItem => Model[i+j].Imagen)" >
                                </a>
                                <p>Click para ver detalles</p>
                            </div>
                            <b>Titulo</b>
                            <br>
                            @Html.DisplayFor(modelItem => Model[i+j].Titulo)
                            <br>
                            <b>Género</b>
                            <br>
                            @Html.DisplayFor(modelItem => Model[i+j].Genero)
                            <br>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div class="text-center">
                                    <button class="btn btn-primary" >
                                        <a asp-action="EditarPelicula" asp-route-id="@Model[i+j].ID">Editar</a> 
                                    </button>
                                </div>
                                
                            }
                        </td>
                    }                
                }
            </tr>    
        }
    </table>
</div>



@if (User.Identity.IsAuthenticated)
{
    <button type="button" class="btn btn-success"><a asp-action="AgregarPelicula"> Registrar Nueva Película</a></button>
}

Views/Pelicula/VistaPelicula.cshtml
@model MovieAppV2.Models.Pelicula
@{
   ViewData["Title"] = "Detalle de la pelicula";
}
<h1 class="text-center">@ViewData["Title"]</h1>

<!--
<style>
.iframe-16-9 {
   position: relative;
   padding-bottom: 56.25%;
   padding-top: 35px;
   height: 0;
   overflow: hidden;
}
.iframe-16-9  iframe {
   position: absolute;
   top:0;
   left: 0;
   width: 100%;
   height: 100%;
}
</style>
-->

<style>
   a {
   color: #ffffff;
   text-decoration: none;
}
   a:hover 
{
   color:#ffffff; 
   text-decoration:none; 
   cursor:pointer;  
}
h2{
   background-color: gray;
   color: white;
   border-radius: 10px;
   text-align: center;
}
.font20{
   font-size: 20px;
   font-weight: 300;
}
.justificado{
   text-align: justify;
   text-
   justify: auto;
}
.checked{
   color: orange;
}
</style>


<div class="container">

   <div class="row">
      <div class="col-5">  
         <div>
            <img width="100%" height="auto" src="@Html.DisplayFor(model => model.Imagen)" alt="Imagen de portada">     
         </div>
         <br>
         <div>
            @if (User.Identity.IsAuthenticated)
            {
               <button class="btn btn-warning">
                  <a asp-controller="Reseña" asp-action="Resena" asp-route-peli="@Model.ID"> Escribir Reseña</a>
               </button>
            }
            @* <button class="btn btn-warning">
               <a asp-controller="Reseña" asp-action="Resena" asp-route-peli="@Model.ID"> Escribir Reseña</a>
            </button> *@
         </div>
      </div>
      <div class="col-7">  
         <dl>
            <dt>
               <h2>
                  Información
               </h2> 
            </dt>
            <br>
            <dt class="font20">
               @Html.DisplayNameFor(model => model.Titulo) :
               @Html.DisplayFor(model => model.Titulo)
            </dt>

            <dt class="font20">
               @Html.DisplayNameFor(model => model.Director) :
               @Html.DisplayFor(model => model.Director)
            </dt>

            <dt class="font20">
               @Html.DisplayNameFor(model => model.Pais) :
               @Html.DisplayFor(model => model.Pais)
            </dt>

            <dt class="font20"> 
               @Html.DisplayNameFor(model => model.Año) :
               @Html.DisplayFor(model => model.Año)
            </dt>

            <dt class="font20">
               @Html.DisplayNameFor(model => model.Genero) :
               @Html.DisplayFor(model => model.Genero)
            </dt>

            <dt class="font20">
               @Html.DisplayNameFor(model => model.Duracion) :
               @Html.DisplayFor(model => model.Duracion)
            </dt>

            <dt class="font20">
               @Html.DisplayNameFor(model => model.Clasificacion) :
               @Html.DisplayFor(model => model.Clasificacion)
            </dt>
            <dt class="font20">
               @Html.DisplayNameFor(model => model.Idioma) :
               @Html.DisplayFor(model => model.Idioma)
            </dt>
         </dl>
         <button type="button" class="btn btn-success">
            <a asp-action="Catalogo"> Regresar al catalogo</a>
         </button>
      </div>
   </div>
   <br>
   <div class="col-12">
      <dt>
         <h2>@Html.DisplayNameFor(model => model.Sinopsis)</h2>
         <div class="justificado">
            @Html.DisplayFor(model => model.Sinopsis)
         </div>
      </dt>
   </div>

   <br>
   
   <h2>@Html.DisplayNameFor(model => model.Trailer)</h2>
   <div class="embed-responsive embed-responsive-16by9">  
      <iframe class="embed-responsive-item" src="@Html.DisplayFor(model => model.Trailer)" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
   </div>
   
   <h2 class="mt-3">
      Reseñas de los usuarios @if (@ViewBag.resenas)
      {
         <a asp-action="VerResenas" asp-controller="Reseña" asp-route-peli="@Model.ID" class="btn btn-warning">Ver todas las reseñas</a>
      }
   </h2>
   @if(@ViewBag.resenas)
   {
      @* <div class="text-center">
         <label for="">&#9734; &#9734; &#9734; &#9734; &#9734; <small>@ViewBag.estrellitas/5</small></label>
         <label for=""> - @ViewBag.nombreusuario</label>
         <br>
         <small><label for="">Publicado: @ViewBag.fecha</label></small>
         <div class="">
            @ViewBag.resenausuario
         </div>
      </div> *@
      <div class="container">
         <div class="row" style="background-color: teal;">
            <div class="col-8">
               Comentario
               <small style="margin-left: 15px;">
                  @ViewBag.fecha
               </small>
            </div>
            <div class="col-4 text-right">
               <label>
               @for (int i = 0; i < ViewBag.estrellitas; i++)
               {
                  <span class="fa fa-star checked"></span>
               }
               @for (int i = 0; i < 5-ViewBag.estrellitas; i++)
               {
                  <span class="fa fa-star"></span>
               }
               </label>
            </div>
         </div>
         <div class="row">
            <div class="col" style="padding-left: 10%; padding-right: 10%; padding-top: 0.5rem; text-align: justify; text-justify: auto;">
               <i>
                  "@ViewBag.resenausuario"
               </i>
            </div>
         </div>
         <div class="row">
            <div class="col-8">                        
            </div>
            <div class="col-4 text-right mb-3">
               <small>
                  <b>
                     ~@ViewBag.nombreusuario~
                  </b>
               </small>
            </div>
         </div>
      </div>

   }else{
      <p>Aun no se han agregado reseñas, puedes agregar una 
         @if (User.Identity.IsAuthenticated)
         {
            <button class="btn btn-warning">
               <a asp-controller="Reseña" asp-action="Resena" asp-route-peli="@Model.ID"> Aqui</a>
            </button>
         }else{
         <button class="btn btn-warning">
            <a asp-action="Registro" asp-controller="Usuario" > Registrandote aqui</a>
         </button>
         }
      </p>
      
   }
   <div class="text-center">
      <button type="button" class="btn btn-success mt-2">
         <a asp-action="Catalogo"> Regresar al catalogo</a>
      </button>
   </div>
   

<!--
  <dl class="dl-horizontal">
      <dt>
         @Html.DisplayNameFor(model => model.Imagen):         
      </dt> 
      <dt>
         <img src="@Html.DisplayFor(model => model.Imagen)" width="35%" alt="Imagen de portada">
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Titulo) :
         @Html.DisplayFor(model => model.Titulo)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Director) :
         @Html.DisplayFor(model => model.Director)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Pais) :
         @Html.DisplayFor(model => model.Pais)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Año) :
         @Html.DisplayFor(model => model.Año) :
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Genero) :
         @Html.DisplayFor(model => model.Genero)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Duracion) :
         @Html.DisplayFor(model => model.Duracion)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Clasificacion) :
         @Html.DisplayFor(model => model.Clasificacion)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Idioma) :
         @Html.DisplayFor(model => model.Idioma)
      </dt>
      <dt>
         @Html.DisplayNameFor(model => model.Sinopsis) :
         @Html.DisplayFor(model => model.Sinopsis)
      </dt>
      <dt class="iframe-16-9">
                                         width="560" height="315"
         <iframe src="@Html.DisplayFor(model => model.Trailer)" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </dt>    
  </dl>
</div>
-->